apps/feed/urls.py
from django.urls import path

from . import views

app_name = 'apps.feed'

urlpatterns = [
    path('', views.Posts.as_view(), name='posts'),
    path('<str:post_id>/', views.Posts.as_view(), name='posts'),
    path('<str:post_id>/edit/', views.EditPost.as_view(), name='post-edit'),
]

apps/user/urls.py
from django.urls import path, include
from django_registration.backends.activation.views import RegistrationView

from .forms import RegistrationForm
from .views import ProfileView

app_name = 'apps.user'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegistrationView.as_view(
        form_class=RegistrationForm,
    ), name="django_registration_register"),
]

simple_feed/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Лента-чат'
admin.site.index_title = 'Зона администрирования'
admin.site.site_title = 'Лента-чат'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.user.urls', namespace='accounts')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.feed.urls', namespace='feed')),
]

apps/feed/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

User = get_user_model()


class Post(MPTTModel):
    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = '-created_at',

    class MPTTMeta:
        order_insertion_by = ['-created_at']

    id = models.UUIDField(verbose_name='идентификатор', primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор', max_length=50, db_index=True)
    body = models.TextField('содержание поста')
    created_at = models.DateTimeField('дата публикации', auto_now_add=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, related_name='children',
                            verbose_name='родительский пост', null=True, blank=True, db_index=True)

    def __str__(self) -> str:
        return f'{self.created_at} | {self.author} | {self.body[:50]}'

apps/user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self) -> str:
        return self.get_full_name() or self.username

apps/feed/forms.py
from django import forms

from . import models


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = 'body',
        widgets = {
            'body': forms.HiddenInput(),
        }

apps/user/forms.py
from django import forms
from django_registration import forms as registration_forms

from . import models


class RegistrationForm(registration_forms.RegistrationFormUniqueEmail):
    class Meta(registration_forms.RegistrationFormUniqueEmail.Meta):
        model = models.User


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = 'first_name', 'last_name', 'email',

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.required = True

apps/feed/views.py
import typing

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, UpdateView

from . import models, forms


class Posts(LoginRequiredMixin, ListView):
    template_name = 'feed/posts.html'
    model = models.Post
    paginate_by = 10

    @property
    def current_post_id(self):
        return self.kwargs.get('post_id')

    def get_queryset(self):
        pid = self.current_post_id
        if pid:
            qs = self.model.objects.filter(parent_id=pid)
        else:
            qs = self.model.objects.root_nodes()
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        pid = self.current_post_id
        if pid:
            context.update(current_post=self.model.objects.get(id=pid))
        context.update(form=forms.PostForm())
        return context

    def post(self, request, *args, **kwargs):
        form = forms.PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.parent_id = self.current_post_id
            post.save()
        return HttpResponseRedirect(request.path_info)


class EditPost(UserPassesTestMixin, UpdateView):
    raise_exception = True
    model = models.Post
    pk_url_kwarg = 'post_id'
    form_class = forms.PostForm
    template_name = 'feed/edit_post.html'

    def test_func(self) -> typing.Optional[bool]:
        if self.request.user.is_staff:
            return True
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('feed:posts', args=(self.object.pk,))

apps/user/views.py
import typing
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView

from . import forms


class ProfileView(LoginRequiredMixin, FormView):
    form_class = forms.ProfileForm
    template_name = 'user/profile.html'

    def form_valid(self, form):
        form.save()
        return self.render_to_response(self.get_context_data(success=True))

    def get_form_kwargs(self) -> typing.Dict[str, typing.Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update(instance=self.request.user)
        return kwargs

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="yandex-verification" content="f57db3036a26bf9d"/>
  <title>Лента новостей</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
        integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>

  <style>
    .header {
      margin-bottom: 0.8rem;
    }

    .menu {
      margin: 0.4em;
    }

    .user {
      margin: 0.8em;
    }
  </style>

  {% block extra_head %}{% endblock %}

  <!-- Yandex.Metrika counter -->
  <script type="text/javascript"> (function (m, e, t, r, i, k, a) {
    m[i] = m[i] || function () {
      (m[i].a = m[i].a || []).push(arguments)
    };
    m[i].l = 1 * new Date();
    k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
  })(window, document, "script", "https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js", "ym");
  ym(68597701, "init", {clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true}); </script>
  <noscript>
    <div><img src="https://mc.yandex.ru/watch/68597701" style="position:absolute; left:-9999px;" alt=""/></div>
  </noscript>
  <!-- /Yandex.Metrika counter -->
</head>
<body>
{% block body %}
  <div class="container">
    {% block header %}
      {% include 'partials/header.html' %}
    {% endblock %}

    {% block main %}{% endblock %}

    {% block footer %}{% endblock %}
  </div>

  {% block extrajs %}{% endblock %}
{% endblock %}
</body>
</html>

templates/django_registration/activation_complete.html
{% extends 'base.html' %}

{% block main %}
  {% include 'partials/title.html' with title='Учетная запись активирована!' %}

  <div>Теперь вы можете войти.</div>
{% endblock %}

templates/django_registration/registration_closed.html
{% extends 'base.html' %}

{% block main %}
  {% include 'partials/title.html' with title='К сожалению, регистрация закрыта' %}
{% endblock %}

templates/django_registration/registration_complete.html
{% extends 'base.html' %}

{% block main %}
  {% include 'partials/title.html' with title='Спасибо за регистрацию!' %}

  <div>На почту отправлено письмо с ссылкой для активации учетной записи.</div>
{% endblock %}

templates/django_registration/registration_form.html
{% extends 'base.html' %}

{% block main %}
  {% include 'partials/title.html' with title='Регистрация' %}
  {% include 'partials/crispy_form.html' with submit_text='Зарегистрироваться' submit_type='btn-success' %}
{% endblock %}

templates/feed/edit_post.html
{% extends 'base.html' %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.css"/>
  <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>
{% endblock %}

{% block main %}
  {% include 'partials/title.html' with title='Редактирование поста' %}

  <div id="editor"></div>
  <div id="post-form-editor">
    {% include 'partials/crispy_form.html' with submit_text='Сохранить' submit_type='btn-primary' %}
  </div>
{% endblock %}

{% block extrajs %}
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>

  <script>
    var editor = new toastui.Editor({
      el: document.querySelector('#editor'),
      height: '500px',
      initialEditType: 'wysiwyg',
      previewStyle: 'horizontal',
      initialValue: `{{ form.body.value|safe }}`,
    });

    window.onload = function () {
      var btn = document.getElementById('post-form-editor').getElementsByTagName('button')[0];
      btn.onclick = function () {
        document.getElementById('id_body').value = editor.getHtml();
      };
    };
  </script>
{% endblock %}

templates/feed/posts.html
{% extends 'base.html' %}

{% load mptt_tags %}
{% load math %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.css"/>
  <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>

  <style>
    .editor {
      display: flex;
      flex-direction: column;
    }

    .collapser {
      margin: 0 auto 1rem auto;
    }

    .post {
      margin-top: 0.8rem;
      margin-bottom: 1.6rem;
    }

    .post__body p, .post__body ol, .post__body ul {
      margin: 0;
    }

    .post__body img {
      max-width: 100%;
    }

    .pages {
      margin-bottom: 1rem;
    }
  </style>
{% endblock %}

{% block main %}
  {% if current_post %}
    {% include 'partials/post.html' with post=current_post need_back=True can_dive_to_thread=False %}
  {% endif %}

  <div class="editor">
    <a class="btn btn-success text-center collapser" data-toggle="collapse"
       href="#collapse-editor" aria-expanded="false" aria-controls="collapse-editor">
      Развернуть/свернуть поле для добавления поста
    </a>
    <div class="collapse" id="collapse-editor">
      <div id="editor"></div>
      <div id="post-form-editor">
        {% include 'partials/crispy_form.html' with submit_text='Добавить пост' submit_type='btn-primary' %}
      </div>
    </div>
  </div>

  {% for post in object_list %}
    {% drilldown_tree_for_node post as drilldown %}

    {% for node, structure in drilldown|tree_info %}
      {% if node.level == post.level %}
        {% include 'partials/post.html' with post=node need_back=False can_dive_to_thread=True %}
      {% endif %}
    {% endfor %}
  {% endfor %}

  {% if paginator.num_pages > 1 %}
    <div class="row justify-content-center pages">
      <div class="btn-group col-auto">
        {% for number in paginator.page_range %}
          <a href="?page={{ number }}"
             class="btn btn-primary{% if number == page_obj.number %} active disabled{% endif %}">
            {{ number }}
          </a>
        {% endfor %}
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block extrajs %}
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
          integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD"
          crossorigin="anonymous"></script>
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>

  <script>
    var editor = new toastui.Editor({
      el: document.querySelector('#editor'),
      height: '300px',
      initialEditType: 'wysiwyg',
      previewStyle: 'horizontal'
    });

    window.onload = function () {
      var btn = document.getElementById('post-form-editor').getElementsByTagName('button')[0];
      btn.onclick = function () {
        document.getElementById('id_body').value = editor.getHtml();
      };

      {# hack: collapsed element has incorrect min-height #}
      for (var el of document.getElementsByClassName('tui-editor-contents')) {
        el.style = 'min-height: 0';
      }
    };
  </script>
{% endblock %}

templates/partials/crispy_form.html
{% load crispy_forms_tags %}

<form method="post" class="row justify-content-center">
  {% csrf_token %}
  {{ form|crispy }}
  {% include 'partials/form_submit_button.html' with text=submit_text type=submit_type %}
</form>

templates/partials/form_submit_button.html
<button type="submit" class="btn {{ type|default:'btn-primary' }} col-auto" style="margin: 1rem;">{{ text }}</button>

templates/partials/header.html
<nav class="navbar navbar-light justify-content-center justify-content-sm-between align-items-center nav header">
  <div class="nav-item-panel">
    <div class="row justify-content-center">
      <div class="col-auto user">
        Привет, {{ user.get_full_name|default:'Незнакомец' }}!
      </div>
    </div>
  </div>
  <div class="nav-item-panel">
    <div class="row justify-content-center">
      {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <a class="btn btn-primary col-auto menu" href="{% url 'admin:index' %}">Панель администратора</a>
        {% endif %}
        <a class="btn btn-secondary col-auto menu" href="{% url 'feed:posts' %}">Главная</a>
        <a class="btn btn-success col-auto menu" href="{% url 'accounts:profile' %}">Профиль</a>
        <a class="btn btn-info col-auto menu" href="{% url 'logout' %}">Выйти</a>
      {% else %}
        <a class="btn btn-primary col-auto menu" href="{% url 'login' %}">Войти</a>
        <a class="btn btn-success col-auto menu" href="{% url 'accounts:django_registration_register' %}">Зарегистрироваться</a>
      {% endif %}
    </div>
  </div>
</nav>

templates/partials/post.html
<div class="card post">
  <div class="card-header">
    <div class="row justify-content-between align-items-center">
      <span class="col-auto post__author">{{ post.author }}</span>

      {% if need_back %}
        <span class="col-auto post__back">
          {% if post.parent %}
            {% url 'feed:posts' post_id=post.parent.id as back_url %}
          {% else %}
            {% url 'feed:posts' as back_url %}
          {% endif %}
          <a href="{{ back_url }}" class="btn btn-success" role="button">Назад</a>
        </span>
      {% endif %}

      <span class="col-auto text-muted post__date">
        {{ post.created_at|date:"d-m-Y" }} {{ post.created_at|time:"H:i:s" }}
      </span>
    </div>
  </div>

  {% if post.author == request.user or request.user.is_staff %}
    <a class="card-header btn" role="button"
       href="{% url 'feed:post-edit' post_id=post.id %}">
      Редактировать&nbsp;
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-chat-text" fill="currentColor"
           xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
      </svg>
    </a>
  {% endif %}

  <div class="card-body post__body">
    {{ post.body|safe }}
  </div>

  {% if can_dive_to_thread %}
    <a class="card-footer btn post__comments post__comments-button"
       href="{% url 'feed:posts' post_id=post.id %}" role="button">
      Комментарии ({{ post.get_descendant_count }})&nbsp;
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-chat-text" fill="currentColor"
           xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"></path>
        <path fill-rule="evenodd"
              d="M4 5.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8zm0 2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"></path>
      </svg>
    </a>
  {% else %}
    <div class="card-footer text-center post__comments post__comments-text">
      Комментарии ({{ post.get_descendant_count }})
    </div>
  {% endif %}

</div>

templates/partials/title.html
<h3 class="text-center" style="margin: 1rem;">{{ title }}</h3>

templates/user/profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block main %}
  {% include 'partials/title.html' with title='Профиль' %}

  {% if success %}
    <div class="alert alert-success text-center" role="alert">
      Данные успешно обновлены
    </div>
  {% endif %}

  <form method="post" class="row justify-content-center">
    {% csrf_token %}
    <div class="row">
      <div class="col-12 col-sm-6">
        {{ form.first_name|as_crispy_field }}
      </div>
      <div class="col-12 col-sm-6">
        {{ form.last_name|as_crispy_field }}
      </div>
    </div>

    <div class="row">
      {{ form.email|as_crispy_field }}
    </div>

    {% include 'partials/form_submit_button.html' with text='Сохранить' type='btn-success' %}
  </form>

  <div class="row justify-content-center">
    <a class="btn btn-primary col-auto menu" href="{% url 'password_change' %}">Сменить пароль</a>
  </div>
{% endblock %}